# Generated by Django 6.0.2 on 2026-03-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(default='', help_text='Ex: 5511999999999', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('ativo', models.BooleanField(default=True)),
                ('valor_aula', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Baia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupada', 'Ocupada')], default='Livre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('slug', models.SlugField(help_text='Identificador único na URL (ex: haras-santa-fe)', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PROPRIO', 'Próprio (Escola)'), ('HOTELARIA', 'Hotelaria (Particular)')], default='PROPRIO', max_length=20)),
                ('status_saude', models.CharField(choices=[('Saudável', 'Saudável'), ('Alerta', 'Alerta'), ('Doente', 'Doente')], default='Saudável', max_length=20)),
                ('onde_dorme', models.CharField(choices=[('BAIA', 'Dorme na Baia'), ('PIQUETE', 'Dorme no Piquete')], default='BAIA', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cavalos/')),
                ('ultima_vacina', models.DateField(blank=True, null=True)),
                ('proxima_vacina', models.DateField(blank=True, null=True)),
                ('ultimo_ferrageamento', models.DateField(blank=True, null=True, verbose_name='Último Ferrageamento / Casqueio')),
                ('proximo_ferrageamento', models.DateField(blank=True, null=True)),
                ('ultima_vermifugacao', models.DateField(blank=True, null=True)),
                ('proxima_vermifugacao', models.DateField(blank=True, null=True)),
                ('historico_medico', models.TextField(blank=True)),
                ('medicamentos_e_remedios', models.TextField(blank=True, help_text='Medicamentos temporários de tratamento')),
                ('racao_tipo', models.CharField(blank=True, help_text='Ex: Guabi Equi-S', max_length=100)),
                ('racao_qtd_manha', models.CharField(blank=True, help_text='Ex: 2kg', max_length=50)),
                ('racao_qtd_noite', models.CharField(blank=True, help_text='Ex: 2kg', max_length=50)),
                ('feno_tipo', models.CharField(blank=True, default='Coast Cross', max_length=100)),
                ('feno_qtd', models.CharField(blank=True, default='À vontade', max_length=100)),
                ('complemento_nutricional', models.TextField(blank=True, help_text='Ex: Vitamina B12, Biotina (Aparecerá em destaque no PDF)')),
                ('mensalidade_baia', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('baia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.baia')),
                ('proprietario', models.ForeignKey(help_text='Se for Próprio, vincular ao gestor ou escola', on_delete=django.db.models.deletion.CASCADE, to='gateagora.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='baia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('NORMAL', 'Aula Normal'), ('RECUPERAR', 'Aula a Recuperar')], default='NORMAL', max_length=15)),
                ('concluida', models.BooleanField(default=False)),
                ('relatorio_treino', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.aluno')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.cavalo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa'),
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('alerta_minimo', models.IntegerField(default=5)),
                ('unidade', models.CharField(default='Unidade', help_text='Ex: KG, Sacos, Fardos', max_length=20)),
                ('fornecedor_contato', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Gestor', 'Gestor/Dono'), ('Veterinario', 'Veterinário'), ('Tratador', 'Tratador'), ('Professor', 'Professor')], default='Tratador', max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='gateagora.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capacidade', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado')], default='Livre', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cavalo',
            name='piquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.piquete'),
        ),
    ]
