# Generated by Django 6.0.3 on 2026-03-06 01:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(default='', help_text='Formato sugerido: 5511999999999', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Telefone deve estar no formato internacional, ex: 5511999999999')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('ativo', models.BooleanField(default=True)),
                ('valor_aula', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Baia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupada', 'Ocupada')], default='Livre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da Unidade', max_length=18, null=True)),
                ('cidade', models.CharField(default='Cidade Exemplo', max_length=100)),
                ('slug', models.SlugField(help_text='Identificador único na URL (ex: haras-santa-fe)', unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='gateagora_e_slug_cbc04f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PROPRIO', 'Próprio (Escola)'), ('HOTELARIA', 'Hotelaria (Particular)')], default='PROPRIO', max_length=20)),
                ('status_saude', models.CharField(choices=[('Saudável', 'Saudável'), ('Alerta', 'Alerta'), ('Doente', 'Doente'), ('Tratamento', 'Em Tratamento')], default='Saudável', max_length=20)),
                ('onde_dorme', models.CharField(choices=[('BAIA', 'Dorme na Baia'), ('PIQUETE', 'Dorme no Piquete')], default='BAIA', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cavalos/')),
                ('raca', models.CharField(choices=[('mang_marchador', 'Mangalarga Marchador'), ('quarto_milha', 'Quarto de Milha'), ('psl', 'Puro Sangue Lusitano'), ('crioulo', 'Crioulo'), ('hipismo', 'Cavalo de Hipismo (BH)'), ('srd', 'Sem Raça Definida')], default='srd', max_length=25)),
                ('peso', models.FloatField(default=450.0, help_text='Peso aproximado para cálculo de ração', validators=[django.core.validators.MinValueValidator(100)])),
                ('fator_atividade', models.CharField(choices=[('0.018', 'Leve (Passeio/Aposentado)'), ('0.025', 'Moderada (Escola/Aulas)'), ('0.035', 'Intensa (Salto/Competição)')], default='0.025', max_length=10)),
                ('tipo_sela', models.CharField(blank=True, help_text='Ex: Sela Salto Americana', max_length=100)),
                ('tipo_cabecada', models.CharField(blank=True, help_text='Ex: Cabeçada com Freio D', max_length=100)),
                ('material_proprio', models.BooleanField(default=False, help_text='Marque se o material for exclusivo do proprietário')),
                ('ultima_vacina', models.DateField(blank=True, null=True)),
                ('ultimo_ferrageamento', models.DateField(blank=True, null=True)),
                ('ultimo_vermifugo', models.DateField(blank=True, null=True)),
                ('ultimo_casqueamento', models.DateField(blank=True, null=True)),
                ('racao_tipo', models.CharField(blank=True, help_text='Ex: Guabi Equi-S', max_length=100)),
                ('racao_qtd_manha', models.CharField(blank=True, help_text='Ex: 2kg', max_length=50)),
                ('racao_qtd_noite', models.CharField(blank=True, help_text='Ex: 2kg', max_length=50)),
                ('feno_tipo', models.CharField(blank=True, default='Coast Cross', max_length=100)),
                ('feno_qtd', models.CharField(blank=True, default='À vontade', max_length=100)),
                ('complemento_nutricional', models.TextField(blank=True)),
                ('mensalidade_baia', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('baia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.baia')),
                ('proprietario', models.ForeignKey(help_text='Se for Próprio, vincular ao gestor ou escola', on_delete=django.db.models.deletion.CASCADE, related_name='cavalos', to='gateagora.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='baia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa'),
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('alerta_minimo', models.IntegerField(default=5)),
                ('unidade', models.CharField(default='Unidade', help_text='Ex: KG, Sacos, Fardos', max_length=20)),
                ('fornecedor_contato', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Gestor', 'Gestor/Dono'), ('Veterinario', 'Veterinário'), ('Tratador', 'Tratador'), ('Professor', 'Professor')], default='Tratador', max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='gateagora.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('local', models.CharField(choices=[('picadeiro_1', 'Picadeiro Principal'), ('picadeiro_2', 'Picadeiro Coberto'), ('pista_salto', 'Pista de Salto')], default='picadeiro_1', max_length=20)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Aula Normal'), ('RECUPERAR', 'Aula a Recuperar')], default='NORMAL', max_length=15)),
                ('concluida', models.BooleanField(default=False)),
                ('relatorio_treino', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='gateagora.aluno')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='gateagora.cavalo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
                ('instrutor', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'Professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_ministradas', to='gateagora.perfil')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Piquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capacidade', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado')], default='Livre', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cavalo',
            name='piquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.piquete'),
        ),
        migrations.CreateModel(
            name='RegistroOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='gateagora.cavalo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Documento', max_length=100)),
                ('tipo', models.CharField(choices=[('GTA', 'GTA'), ('EXAME', 'Exame (Mormo/Anemia)'), ('VACINA', 'Atestado de Vacinação'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_validade', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='docs_cavalos/')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gateagora.cavalo')),
            ],
            options={
                'indexes': [models.Index(fields=['data_validade', 'tipo'], name='gateagora_d_data_va_87810d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='baia',
            index=models.Index(fields=['empresa', 'status'], name='gateagora_b_empresa_397a8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='baia',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_baia_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['empresa', 'nome'], name='gateagora_a_empresa_733f80_idx'),
        ),
        migrations.AddIndex(
            model_name='itemestoque',
            index=models.Index(fields=['empresa', 'nome'], name='gateagora_i_empresa_40f11c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemestoque',
            index=models.Index(fields=['empresa', 'quantidade_atual'], name='gateagora_i_empresa_bab643_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['empresa', 'data', 'tipo'], name='gateagora_m_empresa_eb8d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['empresa', 'data_hora'], name='gateagora_a_empresa_49ca5d_idx'),
        ),
        migrations.AddIndex(
            model_name='piquete',
            index=models.Index(fields=['empresa', 'status'], name='gateagora_p_empresa_015b6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='piquete',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_piquete_empresa_nome'),
        ),
        migrations.AddIndex(
            model_name='cavalo',
            index=models.Index(fields=['empresa', 'status_saude'], name='gateagora_c_empresa_ede893_idx'),
        ),
        migrations.AddIndex(
            model_name='cavalo',
            index=models.Index(fields=['empresa', 'categoria'], name='gateagora_c_empresa_016095_idx'),
        ),
        migrations.AddIndex(
            model_name='registroocorrencia',
            index=models.Index(fields=['cavalo', 'data'], name='gateagora_r_cavalo__9b2d82_idx'),
        ),
    ]
