# Generated by Django 6.0.2 on 2026-03-03 22:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalo',
            name='historico_medico',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='medicamentos_e_remedios',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='proxima_vacina',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='proxima_vermifugacao',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='proximo_ferrageamento',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='ultima_vermifugacao',
        ),
        migrations.AddField(
            model_name='aula',
            name='instrutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas_ministradas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='local',
            field=models.CharField(choices=[('picadeiro_1', 'Picadeiro Principal'), ('picadeiro_2', 'Picadeiro Coberto'), ('pista_salto', 'Pista de Salto')], default='picadeiro_1', max_length=20),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='fator_atividade',
            field=models.CharField(choices=[('0.018', 'Leve (Passeio/Aposentado)'), ('0.025', 'Moderada (Escola/Aulas)'), ('0.035', 'Intensa (Salto/Competição)')], default='0.025', max_length=10),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='material_proprio',
            field=models.BooleanField(default=False, help_text='Marque se o material for exclusivo do proprietário'),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='peso',
            field=models.FloatField(default=450.0, help_text='Peso aproximado para cálculo de ração', validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='raca',
            field=models.CharField(choices=[('mang_marchador', 'Mangalarga Marchador'), ('quarto_milha', 'Quarto de Milha'), ('psl', 'Puro Sangue Lusitano'), ('crioulo', 'Crioulo'), ('hipismo', 'Cavalo de Hipismo (BH)'), ('srd', 'Sem Raça Definida')], default='srd', max_length=25),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='tipo_cabecada',
            field=models.CharField(blank=True, help_text='Ex: Cabeçada com Freio D', max_length=100),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='tipo_sela',
            field=models.CharField(blank=True, help_text='Ex: Sela Salto Americana', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='Cidade Exemplo', max_length=100),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='complemento_nutricional',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='ultimo_ferrageamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoCavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GTA', 'GTA'), ('EXAME', 'Exame (Mormo/Anemia)'), ('VACINA', 'Atestado de Vacinação'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_validade', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='docs_cavalos/')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gateagora.cavalo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='gateagora.cavalo')),
            ],
        ),
    ]
