# Generated by Django 6.0.3 on 2026-03-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0002_eventoagendacavalo_fatura_plano_aluno_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPrazoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_vacina', models.PositiveIntegerField(default=365, help_text='Dias entre vacinações')),
                ('prazo_vermifugo', models.PositiveIntegerField(default=90, help_text='Dias entre vermifugações')),
                ('prazo_ferrageamento', models.PositiveIntegerField(default=60, help_text='Dias entre ferrageamentos')),
                ('prazo_casqueamento', models.PositiveIntegerField(default=60, help_text='Dias entre casqueamentos')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_prazo_manejo', to='gateagora.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Prazos de Manejo',
                'verbose_name_plural': 'Configurações de Prazos de Manejo',
            },
        ),
    ]
