# Generated by Django 6.0.2 on 2026-03-03 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0002_remove_cavalo_historico_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['data_hora']},
        ),
        migrations.AlterModelOptions(
            name='registroocorrencia',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='aula',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_ministradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='baia',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='piquete',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['empresa', 'nome'], name='gateagora_a_empresa_733f80_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['empresa', 'data_hora'], name='gateagora_a_empresa_49ca5d_idx'),
        ),
        migrations.AddIndex(
            model_name='baia',
            index=models.Index(fields=['empresa', 'status'], name='gateagora_b_empresa_397a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='cavalo',
            index=models.Index(fields=['empresa', 'status_saude'], name='gateagora_c_empresa_ede893_idx'),
        ),
        migrations.AddIndex(
            model_name='cavalo',
            index=models.Index(fields=['empresa', 'categoria'], name='gateagora_c_empresa_016095_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocavalo',
            index=models.Index(fields=['data_validade', 'tipo'], name='gateagora_d_data_va_87810d_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['slug'], name='gateagora_e_slug_cbc04f_idx'),
        ),
        migrations.AddIndex(
            model_name='itemestoque',
            index=models.Index(fields=['empresa', 'nome'], name='gateagora_i_empresa_40f11c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemestoque',
            index=models.Index(fields=['empresa', 'quantidade_atual'], name='gateagora_i_empresa_bab643_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['empresa', 'data', 'tipo'], name='gateagora_m_empresa_eb8d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='piquete',
            index=models.Index(fields=['empresa', 'status'], name='gateagora_p_empresa_015b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroocorrencia',
            index=models.Index(fields=['cavalo', 'data'], name='gateagora_r_cavalo__9b2d82_idx'),
        ),
    ]
