# Generated by Django 6.0.2 on 2026-03-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0003_alter_aula_options_alter_registroocorrencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='instrutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'Professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_ministradas', to='gateagora.perfil'),
        ),
    ]
