# Generated by Django 6.0.3 on 2026-03-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0003_configprazomanejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='usa_ferradura',
            field=models.CharField(choices=[('SIM', 'Ferrado (Usa Ferradura)'), ('NAO', 'Descalço (Apenas Casqueamento)')], default='NAO', max_length=3, verbose_name='Usa Ferradura?'),
        ),
    ]
