# Generated by Django 6.0.3 on 2026-03-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0004_cavalo_usa_ferradura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, help_text='WhatsApp com DDD', max_length=20, null=True),
        ),
    ]
