# Generated by Django 6.0.3 on 2026-03-31 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0005_perfil_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HOTELARIA', 'Hotelaria'), ('AULA', 'Aula'), ('VETERINARIO', 'Veterinário'), ('VERMIFUGO', 'Vermífugo'), ('CASQUEIO', 'Casqueio'), ('FERRAGEAMENTO', 'Ferrageamento'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.cavalo', verbose_name='Cavalo')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gateagora.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Item de Fatura',
                'verbose_name_plural': 'Itens de Fatura',
                'ordering': ['tipo', 'data'],
            },
        ),
    ]
