# Generated by Django 6.0.2 on 2026-03-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0006_merge_alter_and_map_instrutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocavalo',
            name='titulo',
            field=models.CharField(default='Documento', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da Unidade', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='status_saude',
            field=models.CharField(choices=[('Saudável', 'Saudável'), ('Alerta', 'Alerta'), ('Doente', 'Doente'), ('Tratamento', 'Em Tratamento')], default='Saudável', max_length=20),
        ),
    ]
