# Generated by Django 6.0.3 on 2026-04-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0006_itemfatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gateagora.fatura'),
        ),
    ]
