# Generated by Django 6.0.3 on 2026-04-01 20:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0007_alter_itemfatura_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='gateagora.aluno'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='tipo',
            field=models.CharField(choices=[('HOTELARIA', 'Hotelaria'), ('AULA', 'Aula'), ('VETERINARIO', 'Veterinário'), ('VERMIFUGO', 'Vermífugo'), ('CASQUEIO', 'Casqueio'), ('FERRAGEAMENTO', 'Ferrageamento'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
