# Generated by Django 6.0.3 on 2026-04-02 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0008_alter_fatura_aluno_alter_fatura_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='consumo_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo médio por dia (deixe em branco se não aplicável)', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste (Fechamento do Dia)')], max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gateagora.itemestoque')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'data', 'item'], name='gateagora_m_empresa_6bb9c8_idx')],
            },
        ),
    ]
