# Generated by Django 6.0.3 on 2026-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0009_itemestoque_consumo_diario_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('Gestor', 'Gestor/Dono'), ('Veterinario', 'Veterinário'), ('Tratador', 'Tratador'), ('Professor', 'Professor'), ('Aluno', 'Aluno/Cliente')], default='Tratador', max_length=50),
        ),
    ]
