# Generated by Django 6.0.3 on 2026-04-14 23:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0010_alter_perfil_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPrecoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobrar_vacina', models.BooleanField(default=False)),
                ('valor_vacina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cobrar_vermifugo', models.BooleanField(default=False)),
                ('valor_vermifugo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cobrar_ferrageamento', models.BooleanField(default=False)),
                ('valor_ferrageamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cobrar_casqueamento', models.BooleanField(default=False)),
                ('valor_casqueamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_preco_manejo', to='gateagora.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Preços de Manejo',
                'verbose_name_plural': 'Configurações de Preços de Manejo',
            },
        ),
    ]
