# Generated by Django 6.0.3 on 2026-04-20 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0011_configprecomanejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configprazomanejo',
            name='prazo_confirmacao_horas',
            field=models.PositiveIntegerField(default=24, help_text='Horas antes da aula dentro das quais o aluno pode confirmar presença (0 = sem prazo)'),
        ),
        migrations.CreateModel(
            name='ConfirmacaoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='gateagora.aluno')),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao', to='gateagora.aula')),
            ],
            options={
                'verbose_name': 'Confirmação de Presença',
                'verbose_name_plural': 'Confirmações de Presença',
            },
        ),
    ]
