# Generated by Django 6.0.3 on 2026-04-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0012_configprazomanejo_prazo_confirmacao_horas_and_more'),
    ]

    operations = [
    ]
