# Generated by Django 6.0.3 on 2026-04-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0013_auto_20260420_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='perfil_usuario',
            field=models.OneToOneField(blank=True, help_text='Perfil de acesso do aluno ao sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_vinculado', to='gateagora.perfil', verbose_name='Login do Aluno'),
        ),
    ]
