# Generated by Django 6.0.3 on 2026-04-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0014_aluno_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='nome_turma',
            field=models.CharField(blank=True, help_text="Preencha apenas para aulas em grupo (ex: 'Turma Iniciantes Sábado')", max_length=100),
        ),
        migrations.AddField(
            model_name='aula',
            name='vagas_maximas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Capacidade máxima da turma. Deixe em branco para aulas individuais.', null=True),
        ),
        migrations.CreateModel(
            name='InscricaoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='gateagora.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='gateagora.aula')),
            ],
            options={
                'verbose_name': 'Inscrição em Aula',
                'verbose_name_plural': 'Inscrições em Aulas',
                'indexes': [models.Index(fields=['aula', 'aluno'], name='gateagora_i_aula_id_0215c6_idx')],
                'unique_together': {('aula', 'aluno')},
            },
        ),
    ]
