# Generated by Django 6.0.3 on 2026-04-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0015_aula_nome_turma_aula_vagas_maximas_inscricaoaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacaopresenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes_presenca', to='gateagora.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmacaopresenca',
            unique_together={('aula', 'aluno')},
        ),
        migrations.AddIndex(
            model_name='confirmacaopresenca',
            index=models.Index(fields=['aula', 'aluno'], name='gateagora_c_aula_id_9f4c00_idx'),
        ),
    ]
