# Generated by Django 6.0.3 on 2026-04-28 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0016_alter_confirmacaopresenca_aula_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricaoaula',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='inscricaoaula',
            name='gateagora_i_aula_id_0215c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='confirmacaopresenca',
            name='gateagora_c_aula_id_9f4c00_idx',
        ),
        migrations.AlterUniqueTogether(
            name='confirmacaopresenca',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aula',
            name='nome_turma',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='vagas_maximas',
        ),
        migrations.AddField(
            model_name='aluno',
            name='melhor_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Melhor Streak'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='streak_atual',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Semanas Seguidas'),
        ),
        migrations.AlterField(
            model_name='confirmacaopresenca',
            name='aula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao', to='gateagora.aula'),
        ),
        migrations.DeleteModel(
            name='InscricaoAula',
        ),
    ]
