# Generated by Django 6.0.3 on 2026-04-28 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0017_alter_inscricaoaula_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição em Aula',
                'verbose_name_plural': 'Inscrições em Aulas',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='nome_turma',
            field=models.CharField(blank=True, help_text='Preencha apenas para aulas em grupo', max_length=100),
        ),
        migrations.AddField(
            model_name='aula',
            name='vagas_maximas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Capacidade máxima da turma. Deixe em branco para aulas individuais.', null=True),
        ),
        migrations.AlterField(
            model_name='confirmacaopresenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes_presenca', to='gateagora.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmacaopresenca',
            unique_together={('aula', 'aluno')},
        ),
        migrations.AddIndex(
            model_name='confirmacaopresenca',
            index=models.Index(fields=['aula', 'aluno'], name='gateagora_c_aula_id_9f4c00_idx'),
        ),
        migrations.AddField(
            model_name='inscricaoaula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='gateagora.aluno'),
        ),
        migrations.AddField(
            model_name='inscricaoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='gateagora.aula'),
        ),
        migrations.AddIndex(
            model_name='inscricaoaula',
            index=models.Index(fields=['aula', 'aluno'], name='gateagora_i_aula_id_0215c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoaula',
            unique_together={('aula', 'aluno')},
        ),
    ]
