# Generated by Django 6.0.2 on 2026-05-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0018_inscricaoaula_aula_nome_turma_aula_vagas_maximas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricaoaula',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='inscricaoaula',
            name='gateagora_i_aula_id_0215c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='confirmacaopresenca',
            name='gateagora_c_aula_id_9f4c00_idx',
        ),
        migrations.AlterUniqueTogether(
            name='confirmacaopresenca',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='melhor_streak',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='streak_atual',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='nome_turma',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='vagas_maximas',
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Data de validade do produto (opcional). Deixe em branco se não aplicável.', null=True),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='lote',
            field=models.CharField(blank=True, help_text='Número do lote (opcional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='confirmacaopresenca',
            name='aula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao', to='gateagora.aula'),
        ),
        migrations.AddIndex(
            model_name='itemestoque',
            index=models.Index(fields=['empresa', 'data_validade'], name='gateagora_i_empresa_735102_idx'),
        ),
        migrations.DeleteModel(
            name='InscricaoAula',
        ),
    ]
