# Generated by Django 6.0.3 on 2026-05-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0019_alter_inscricaoaula_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['data_validade', 'data_entrada'],
            },
        ),
        migrations.RemoveIndex(
            model_name='itemestoque',
            name='gateagora_i_empresa_735102_idx',
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='consumo_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo médio por dia', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='gateagora.itemestoque', verbose_name='Item de Estoque'),
        ),
        migrations.AddIndex(
            model_name='loteestoque',
            index=models.Index(fields=['item', 'data_validade', 'ativo'], name='gateagora_l_item_id_1ec481_idx'),
        ),
    ]
