# Generated by Django 6.0.2 on 2026-05-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0020_loteestoque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='itemestoque',
            name='lote',
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='consumo_diario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consumo médio diário (para calcular dias restantes)', max_digits=6),
        ),
    ]
