# Generated by Django 6.0.3 on 2026-05-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0021_remove_itemestoque_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='cavalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='gateagora.cavalo'),
        ),
    ]
