# Generated by Django 6.0.3 on 2026-05-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0022_alter_aula_cavalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='melhor_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Melhor Sequência'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='streak_atual',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequência Atual'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='melhor_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Melhor Sequência'),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='streak_atual',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequência Atual'),
        ),
    ]
