# Generated by Django 6.0.3 on 2026-05-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0023_remove_aluno_foto_remove_aluno_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='melhor_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='streak_atual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
