# Generated by Django 6.0.3 on 2026-05-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0024_alter_aluno_melhor_streak_alter_aluno_streak_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configprecomanejo',
            options={'verbose_name': '🧑\u200d🌾Configuração de Preços de Manejo⚙️', 'verbose_name_plural': '🧑\u200d🌾Configurações de Preços de Manejo⚙️'},
        ),
    ]
