# Generated by Django 6.0.3 on 2026-05-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0025_alter_configprecomanejo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configprecomanejo',
            options={'verbose_name': 'Configuração de Preços de Manejo🧑\u200d🌾⚙️', 'verbose_name_plural': 'Configurações de Preços de Manejo🧑\u200d🌾⚙️'},
        ),
    ]
