# Generated by Django 6.0.2 on 2026-05-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0026_alter_configprecomanejo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno 🧑\u200d🎓', 'verbose_name_plural': 'Alunos 🧑\u200d🎓'},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['data_hora'], 'verbose_name': 'Aula 📅', 'verbose_name_plural': 'Aulas 📅'},
        ),
        migrations.AlterModelOptions(
            name='baia',
            options={'verbose_name': 'Baia 🛖', 'verbose_name_plural': 'Baias 🛖'},
        ),
        migrations.AlterModelOptions(
            name='cavalo',
            options={'ordering': ['nome'], 'verbose_name': 'Cavalo 🐴', 'verbose_name_plural': 'Cavalos 🐴'},
        ),
        migrations.AlterModelOptions(
            name='configprecomanejo',
            options={'verbose_name': 'Configuração de Preços de Manejo 👨\u200d🌾 💲', 'verbose_name_plural': 'Configurações de Preços de Manejo 👨\u200d🌾 💲'},
        ),
        migrations.AlterModelOptions(
            name='documentocavalo',
            options={'verbose_name': 'Documento de Cavalo 📄', 'verbose_name_plural': 'Documentos de Cavalos 📄'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa 🏢', 'verbose_name_plural': 'Empresas 🏢'},
        ),
        migrations.AlterModelOptions(
            name='eventoagendacavalo',
            options={'verbose_name': 'Evento na Agenda 📒', 'verbose_name_plural': 'Eventos agenda cavalos 📒'},
        ),
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Fatura 💳', 'verbose_name_plural': 'Faturas 💳'},
        ),
        migrations.AlterModelOptions(
            name='itemestoque',
            options={'verbose_name': 'Item de Estoque 📦', 'verbose_name_plural': 'Item estoques 📦'},
        ),
        migrations.AlterModelOptions(
            name='loteestoque',
            options={'ordering': ['data_validade', 'data_entrada'], 'verbose_name': 'Lote de Estoque 🏷️', 'verbose_name_plural': 'Lotes de Estoque 🏷️'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaofinanceira',
            options={'verbose_name': 'Movimentação Financeira 💵', 'verbose_name_plural': 'Movimentação financeiras 💵'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil 👤', 'verbose_name_plural': 'Perfils 👤'},
        ),
        migrations.AlterModelOptions(
            name='piquete',
            options={'verbose_name': 'Piquete 🌳', 'verbose_name_plural': 'Piquetes 🌳'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Plano 📑', 'verbose_name_plural': 'Planos 📑'},
        ),
        migrations.AlterModelOptions(
            name='registroocorrencia',
            options={'ordering': ['-data'], 'verbose_name': 'Registro de Ocorrência 👨\u200d⚕️', 'verbose_name_plural': 'Registro ocorrencias 👨\u200d⚕️'},
        ),
    ]
