# Generated by Django 6.0.2 on 2026-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0027_alter_aluno_options_alter_aula_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/', verbose_name='Foto do Aluno'),
        ),
    ]
