# Generated by Django 6.0.2 on 2026-05-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0028_aluno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacaCavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Raça de Cavalo 🐴',
                'verbose_name_plural': 'Raças de Cavalos 🐴',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, help_text='⚠️ Tamanho máximo: 5MB. Formatos aceitos: JPG, PNG.', null=True, upload_to='alunos/', verbose_name='Foto do Aluno'),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='foto',
            field=models.ImageField(blank=True, help_text='⚠️ Tamanho máximo: 5MB. Formatos aceitos: JPG, PNG.', null=True, upload_to='cavalos/', verbose_name='Foto do Cavalo'),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.racacavalo', verbose_name='Raça'),
        ),
    ]
