# Generated by Django 6.0.3 on 2026-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0030_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='WhatsApp com DDD', max_length=20, null=True),
        ),
    ]
