# Generated by Django 6.0.3 on 2026-05-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0031_add_telefone_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'Fornecedor 🚚', 'verbose_name_plural': 'Fornecedores 🚚'},
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='fornecedor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.fornecedor', verbose_name='Fornecedor Padrão'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='fornecedor_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Fornecedor'),
        ),
    ]
