# Generated by Django 6.0.3 on 2026-09-10 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0033_itemestoque_lote_economico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Aula Normal'), ('RECUPERAR', 'Aula a Recuperar'), ('TREINO_INTERNO', 'Treino Interno (sem custo)')], default='NORMAL', max_length=15),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUNO', 'Checklist do Aluno'), ('LOGISTICA', 'Checklist de Logística (Gestor/Tratador)')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
            options={
                'verbose_name': 'Item de Checklist ✅',
                'verbose_name_plural': 'Itens de Checklist ✅',
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPreenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='gateagora.aula')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.checklistitem')),
            ],
            options={
                'verbose_name': 'Checklist Preenchido',
                'verbose_name_plural': 'Checklists Preenchidos',
                'unique_together': {('aula', 'item')},
            },
        ),
    ]
