# Generated by Django 6.0.3 on 2026-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0034_alter_aula_tipo_checklistitem_checklistpreenchido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='fornecedor_contato',
        ),
        migrations.RemoveField(
            model_name='itemestoque',
            name='fornecedor_padrao',
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='fornecedor_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='alerta_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='unidade',
            field=models.CharField(default='Pares', max_length=20),
        ),
    ]
