# Generated by Django 6.0.3 on 2026-09-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0035_remove_itemestoque_fornecedor_contato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='fornecedor_telefone',
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='fornecedor_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Fornecedor'),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='fornecedor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.fornecedor', verbose_name='Fornecedor Padrão'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='alerta_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='unidade',
            field=models.CharField(default='Unidade', help_text='Ex: KG, Sacos, Fardos', max_length=20),
        ),
    ]
