# Generated by Django 6.0.3 on 2026-09-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0036_remove_itemestoque_fornecedor_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='local',
            field=models.CharField(choices=[('picadeiro_1', 'Picadeiro Principal'), ('picadeiro_2', 'Picadeiro Coberto'), ('pista_salto', 'Pista de Salto'), ('Competição', 'Competição')], default='picadeiro_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Aula Normal'), ('RECUPERAR', 'Aula a Recuperar'), ('TREINO_INTERNO', 'Treino Interno (sem custo)'), ('TREINO_EXTERNO', 'Competição')], default='NORMAL', max_length=15),
        ),
        migrations.CreateModel(
            name='LocalAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateagora.empresa')),
            ],
            options={
                'verbose_name': 'Local de Aula 📍',
                'verbose_name_plural': 'Locais de Aula 📍',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='local_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateagora.localaula', verbose_name='Local (novo)'),
        ),
    ]
