# Generated by Django 6.0.3 on 2026-09-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0037_alter_aula_local_alter_aula_tipo_localaula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='cabecada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='gateagora.cabecada', verbose_name='Cabeçada Utilizada'),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='cabecada_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos_padrao', to='gateagora.cabecada', verbose_name='Cabeçada Padrão'),
        ),
        migrations.AddField(
            model_name='aula',
            name='sela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='gateagora.sela', verbose_name='Sela Utilizada'),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='sela_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos_padrao', to='gateagora.sela', verbose_name='Sela Padrão'),
        ),
    ]
