# Generated by Django 6.0.3 on 2026-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0038_cabecada_sela_aula_cabecada_cavalo_cabecada_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='local',
            field=models.CharField(choices=[('picadeiro_1', 'Picadeiro Principal'), ('picadeiro_2', 'Picadeiro Coberto'), ('pista_salto', 'Pista de Salto'), ('competicao', 'Competição')], default='picadeiro_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Aula Normal'), ('RECUPERAR', 'Aula a Recuperar'), ('TREINO_INTERNO', 'Treino Interno (sem custo)'), ('TREINO_EXTERNO', 'Competição')], default='NORMAL', max_length=30),
        ),
    ]
