# Generated by Django 6.0.3 on 2026-09-27 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0039_alter_aula_local_alter_aula_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configprazomanejo',
            name='prazo_confirmacao_horas',
        ),
        migrations.AddField(
            model_name='configprazomanejo',
            name='mostrar_aviso_mesmo_dia',
            field=models.BooleanField(default=True, help_text='Se True: mostra aviso quando operação ocorre no mesmo dia da aula'),
        ),
        migrations.AddField(
            model_name='configprazomanejo',
            name='permitir_confirmacao_mesmo_dia',
            field=models.BooleanField(default=True, help_text='Se True: aluno pode confirmar no próprio dia da aula (com aviso). Se False: só antes do dia.'),
        ),
        migrations.CreateModel(
            name='LimpezaBaia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horario', models.TimeField(blank=True, help_text='Horário da limpeza', null=True)),
                ('observacao', models.TextField(blank=True, help_text='Observações adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('baia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpezas', to='gateagora.baia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpezas_baia', to='gateagora.empresa')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Quem realizou a limpeza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas_realizadas', to='gateagora.perfil')),
            ],
            options={
                'verbose_name': 'Limpeza de Baia 🧹',
                'verbose_name_plural': 'Limpezas de Baias 🧹',
                'ordering': ['-data', '-horario'],
                'indexes': [models.Index(fields=['empresa', 'baia', 'data'], name='gateagora_l_empresa_c7aa4b_idx'), models.Index(fields=['data'], name='gateagora_l_data_94166f_idx')],
                'unique_together': {('baia', 'data')},
            },
        ),
        migrations.CreateModel(
            name='TrocaTotalCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('periodicidade_dias', models.PositiveIntegerField(default=7, help_text='A cada quantos dias fazer nova troca')),
                ('proxima_data', models.DateField(help_text='Data calculada para a próxima troca')),
                ('status', models.CharField(choices=[('EM_DIA', 'Em Dia'), ('PROXIMA', 'Próxima se aproximando'), ('VENCIDA', 'Vencida')], default='EM_DIA', help_text='Status da próxima troca', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('baia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_cama', to='gateagora.baia')),
                ('cavalo', models.ForeignKey(blank=True, help_text='Cavalo que estava na baia no momento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_cama_registros', to='gateagora.cavalo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_cama', to='gateagora.empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_cama_realizadas', to='gateagora.perfil')),
            ],
            options={
                'verbose_name': 'Troca Total da Cama 🛏️',
                'verbose_name_plural': 'Trocas Totais da Cama 🛏️',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['empresa', 'baia', 'data'], name='gateagora_t_empresa_2a4b42_idx'), models.Index(fields=['status', 'proxima_data'], name='gateagora_t_status_576568_idx')],
            },
        ),
    ]
