# Generated by Django 6.0.3 on 2026-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0040_remove_configprazomanejo_prazo_confirmacao_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='agendado_por_proprietario',
            field=models.BooleanField(default=False, help_text='True se o proprietário do cavalo agendou esta aula com seu próprio cavalo'),
        ),
    ]
