# Generated by Django 6.0.3 on 2026-09-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0041_aula_agendado_por_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfatura',
            name='tipo',
            field=models.CharField(choices=[('HOTELARIA', 'Hotelaria'), ('AULA', 'Aula'), ('VETERINARIO', 'Veterinário'), ('VERMIFUGO', 'Vermífugo'), ('CASQUEIO', 'Casqueio'), ('FERRAGEAMENTO', 'Ferrageamento'), ('TROCA_CAMA', 'Troca de Cama'), ('OUTROS', 'Outros')], max_length=20),
        ),
    ]
