# Generated by Django 6.0.3 on 2026-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0042_alter_itemfatura_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='ultima_troca_cama',
            field=models.DateField(blank=True, null=True),
        ),
    ]
