# Generated by Django 6.0.3 on 2026-09-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateagora', '0043_cavalo_ultima_troca_cama'),
    ]

    operations = [
        migrations.AddField(
            model_name='configprazomanejo',
            name='prazo_troca_cama',
            field=models.PositiveIntegerField(default=45, help_text='Dias entre trocas de cama'),
        ),
    ]
